//
//  PayWalletPresenter.swift
//  Payment
//
//  Created by ARPIT  SRIVASTAVA on 12/12/18.
//  Copyright (c) 2018 Arpit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PayWalletPresentationLogic {
    func presentInfo(response: PayWallet.Info.Response)
}

class PayWalletPresenter: PayWalletPresentationLogic {
    weak var viewController: PayWalletDisplayLogic?
    
    var currencyFormatter: NumberFormatter {
        let currencyFormatter = NumberFormatter()
        currencyFormatter.usesGroupingSeparator = true
        currencyFormatter.numberStyle = .currency
        currencyFormatter.maximumFractionDigits = 1
        currencyFormatter.locale = Locale(identifier: "en_IN")
        return currencyFormatter
    }
    

    
    // MARK: Do Info
    
    func presentInfo(response: PayWallet.Info.Response) {
        let infoModel = getWalletInfoViewModel(response: response)
        let viewModel = PayWallet.Info.ViewModel(title: response.title,
                                                 walletInfo: infoModel)
        viewController?.displayInfo(viewModel: viewModel)
    }
    
    private func getWalletInfoViewModel(response: PayWallet.Info.Response) -> [PayWallet.Info.ViewModel.WalletViewModel] {
        let info = response.walletInfo
        let walletInfo = info.map { PayWallet.Info.ViewModel.WalletViewModel(title: $0.title, amount: currencyFormatter.string(from: NSNumber(value: $0.amount)) ?? EMPTYSTRING) }
        return walletInfo
    }
}
