//
//  PayWalletInteractor.swift
//  Payment
//
//  Created by ARPIT  SRIVASTAVA on 12/12/18.
//  Copyright (c) 2018 Arpit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PayWalletBusinessLogic {
    func doSomething(request: PayWallet.Something.Request)
}

protocol PayWalletDataStore {
    //var name: String { get set }
}

class PayWalletInteractor: PayWalletBusinessLogic, PayWalletDataStore {
    var presenter: PayWalletPresentationLogic?
    var worker: PayWalletWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: PayWallet.Something.Request) {
        worker = PayWalletWorker()
        worker?.doSomeWork()
        
        let response = PayWallet.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
