//
//  PayWalletInteractor.swift
//  Payment
//
//  Created by ARPIT  SRIVASTAVA on 12/12/18.
//  Copyright (c) 2018 Arpit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PayWalletBusinessLogic {
    func fetchInfo(request: PayWallet.Info.Request)
}

protocol PayWalletDataStore {
    //var name: String { get set }
}

class PayWalletInteractor: PayWalletBusinessLogic, PayWalletDataStore {
    var presenter: PayWalletPresentationLogic?
    var worker: PayWalletWorker?
    //var name: String = ""
    
    // MARK: Do Info
    
    func fetchInfo(request: PayWallet.Info.Request) {
        let info = getWalletInfo()
        let response = PayWallet.Info.Response(title: "Freecharge Wallet",
                                               walletInfo: info)
        presenter?.presentInfo(response: response)
    }
    
    private func getWalletInfo() -> [PayWallet.Info.Response.WalletResponse] {
        var temp: [PayWallet.Info.Response.WalletResponse] = []
        temp += [PayWallet.Info.Response.WalletResponse(title: "Amount to be paid",
                                                        amount: 390)]
        temp += [PayWallet.Info.Response.WalletResponse(title: "Wallet Balance",
                                                        amount: 39)]
        return temp
    }
}
