//
//  PayWalletViewController.swift
//  Payment
//
//  Created by ARPIT  SRIVASTAVA on 12/12/18.
//  Copyright (c) 2018 Arpit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PayWalletDisplayLogic: class {
    func displayInfo(viewModel: PayWallet.Info.ViewModel)
}

class PayWalletViewController: UIViewController, PayWalletDisplayLogic {
    var interactor: PayWalletBusinessLogic?
    var router: (NSObjectProtocol & PayWalletRoutingLogic & PayWalletDataPassing)?
    var walletInfo: [PayWallet.Info.ViewModel.WalletViewModel] = []
    
    @IBOutlet weak var containerView: UIView!
    @IBOutlet weak var tblView: UITableView!
    @IBOutlet weak var amountTextField: UITextField!
    @IBOutlet weak var paynAddButton: UIButton!
    @IBOutlet weak var footerView: UIView!
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = PayWalletInteractor()
        let presenter = PayWalletPresenter()
        let router = PayWalletRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        fetchInfo()
//        navigationItem.title = "Wallet"
        containerView.layer.cornerRadius = 5
        containerView.dropShadow()
        paynAddButton.layer.cornerRadius = 5
        tblView.contentInset = UIEdgeInsets(top: 45, left: 0, bottom: 0, right: 0)
    }
    
    // MARK: Do Info
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func fetchInfo() {
        let request = PayWallet.Info.Request()
        interactor?.fetchInfo(request: request)
    }
    
    func displayInfo(viewModel: PayWallet.Info.ViewModel) {
        navigationItem.title = viewModel.title
        walletInfo = viewModel.walletInfo
        tblView.reloadData()
    }
}

extension PayWalletViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return walletInfo.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: PayWalletConstants.Values.IdentifierNames.PayWalletTableViewCell, for: indexPath) as! PayWalletTableViewCell
        cell.configureCell(with: walletInfo[indexPath.row])
        return cell
    }
}
