//
//  PayWalletModels.swift
//  Payment
//
//  Created by ARPIT  SRIVASTAVA on 12/12/18.
//  Copyright (c) 2018 Arpit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PayWallet {
    // MARK: Use cases
    
    enum Info {
        struct Request {
        }
        struct Response {
            struct WalletResponse {
                var title: String
                var amount: Int
            }
            var title: String
            var walletInfo: [WalletResponse]
        }
        struct ViewModel {
            struct WalletViewModel {
                var title: String
                var amount: String
            }
            var title: String
            var walletInfo: [WalletViewModel]
        }
    }
}
