//
//  LinkWalletInteractor.swift
//  Payment
//
//  Created by ARPIT  SRIVASTAVA on 12/12/18.
//  Copyright (c) 2018 Arpit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LinkWalletBusinessLogic {
    func doSomething(request: LinkWallet.Something.Request)
}

protocol LinkWalletDataStore {
    //var name: String { get set }
}

class LinkWalletInteractor: LinkWalletBusinessLogic, LinkWalletDataStore {
    var presenter: LinkWalletPresentationLogic?
    var worker: LinkWalletWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: LinkWallet.Something.Request) {
        worker = LinkWalletWorker()
        worker?.doSomeWork()
        
        let response = LinkWallet.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
