//
//  UPIInteractor.swift
//  Payment
//
//  Created by ARPIT  SRIVASTAVA on 10/12/18.
//  Copyright (c) 2018 Arpit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UPIBusinessLogic {
    func doSomething(request: UPI.Something.Request)
}

protocol UPIDataStore {
    //var name: String { get set }
}

class UPIInteractor: UPIBusinessLogic, UPIDataStore {
    var presenter: UPIPresentationLogic?
    var worker: UPIWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: UPI.Something.Request) {
        worker = UPIWorker()
        worker?.doSomeWork()
        
        let response = UPI.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
