//
//  UPIPresenter.swift
//  Payment
//
//  Created by ARPIT  SRIVASTAVA on 10/12/18.
//  Copyright (c) 2018 Arpit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UPIPresentationLogic {
    func presentSomething(response: UPI.Something.Response)
}

class UPIPresenter: UPIPresentationLogic {
    weak var viewController: UPIDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: UPI.Something.Response) {
        let viewModel = UPI.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
