//
//  UPIWorker.swift
//  Payment
//
//  Created by ARPIT  SRIVASTAVA on 10/12/18.
//  Copyright (c) 2018 Arpit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class UPIWorker {
    func doSomeWork() {
    }
}
