//
//  PaymentHomeViewController.swift
//  Payment
//
//  Created by ARPIT  SRIVASTAVA on 03/12/18.
//  Copyright (c) 2018 Arpit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PaymentHomeDisplayLogic: class {
    func displayPaymentOptions(viewModel: PaymentHome.PaymentOptions.ViewModel)
}

class PaymentHomeViewController: UIViewController, PaymentHomeDisplayLogic {
    var interactor: PaymentHomeBusinessLogic?
    var router: (NSObjectProtocol & PaymentHomeRoutingLogic & PaymentHomeDataPassing)?
    
    private var summary: [Identifiable] = []
    @IBOutlet weak var tableView: UITableView!
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = PaymentHomeInteractor()
        let presenter = PaymentHomePresenter()
        let router = PaymentHomeRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        fetchPaymentOptions()
    }
    
    // MARK: Do something
    
    func fetchPaymentOptions() {
        let request = PaymentHome.PaymentOptions.Request()
        interactor?.fetchPaymentOptions(request: request)
    }
    
    func displayPaymentOptions(viewModel: PaymentHome.PaymentOptions.ViewModel) {
        summary = viewModel.summary
        tableView.reloadData()
    }
}

extension PaymentHomeViewController: UITableViewDataSource {
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return summary.count
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        var rows = 1
        let identifier = summary[section].identifier
        switch identifier {
        case PaymentHomeConstants.Values.IdentifierNames.WalletsSection:
            let model = summary[section] as! PaymentHome.PaymentOptions.ViewModel.WalletsViewModel
            rows = model.wallets.count
        case PaymentHomeConstants.Values.IdentifierNames.SavedCardsSection:
            let model = summary[section] as! PaymentHome.PaymentOptions.ViewModel.CardsViewModel
            rows = model.cards.count
        default:
            break
        }
        return rows
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        var cell = UITableViewCell()
        let identifier = summary[indexPath.section].identifier
        switch identifier {
        case PaymentHomeConstants.Values.IdentifierNames.HeaderTableCell:
            let lCell = tableView.dequeueReusableCell(withIdentifier: identifier,
                                                      for: indexPath) as! HeaderTableCell
            let model = summary[indexPath.section] as! PaymentHome.PaymentOptions.ViewModel.HeaderViewModel
            lCell.configureCellWithModel(model)
            cell = lCell
        case PaymentHomeConstants.Values.IdentifierNames.FooterTableCell:
            let lCell = tableView.dequeueReusableCell(withIdentifier: identifier,
                                                      for: indexPath) as! FooterTableCell
            let model = summary[indexPath.section] as! PaymentHome.PaymentOptions.ViewModel.FooterViewModel
            lCell.configureCellWithModel(model)
            cell = lCell
        case PaymentHomeConstants.Values.IdentifierNames.UPITableCell:
            let lCell = tableView.dequeueReusableCell(withIdentifier: identifier,
                                                      for: indexPath) as! UPITableCell
            cell = lCell
        case PaymentHomeConstants.Values.IdentifierNames.SavedCardsSection:
            let model = summary[indexPath.section] as! PaymentHome.PaymentOptions.ViewModel.CardsViewModel
            let cardModel = model.cards[indexPath.row]
            let lCell = tableView.dequeueReusableCell(withIdentifier: PaymentHomeConstants.Values.IdentifierNames.SavedCardTableCell,
                                                      for: indexPath) as! SavedCardTableCell
            lCell.configureCellWithModel(cardModel)
            cell = lCell

        case PaymentHomeConstants.Values.IdentifierNames.WalletsSection:
            let model = summary[indexPath.section] as! PaymentHome.PaymentOptions.ViewModel.WalletsViewModel
            let walletModel = model.wallets[indexPath.row]
            let lCell = tableView.dequeueReusableCell(withIdentifier: PaymentHomeConstants.Values.IdentifierNames.WalletTableCell,
                                                      for: indexPath) as! WalletTableCell
            lCell.configureCellWithModel(walletModel)
            cell = lCell
        case PaymentHomeConstants.Values.IdentifierNames.NetBanksTableCell:
            let model = summary[indexPath.section] as! PaymentHome.PaymentOptions.ViewModel.PreferredBanksViewModel
            let lCell = tableView.dequeueReusableCell(withIdentifier: identifier,
                                                      for: indexPath) as! NetBanksTableCell
            lCell.configureCellWithModel(model.banks)
            cell = lCell
        default:
            break
        }
        return cell
    }
}

extension PaymentHomeViewController: UITableViewDelegate {
    
    public func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        var height: CGFloat = 5
//        let identifier = summary[section].identifier
//
//        switch identifier {
//        case HomeNewKeys.IdentifierNames.PlatinumTableCell:
//            break
//        default:
//            break
//        }
        return height
    }
    
    public func tableView(_ tableView: UITableView, heightForFooterInSection section: Int) -> CGFloat {
        var height: CGFloat = CGFloat.leastNonzeroMagnitude
//        let identifier = summary[section].identifier
//        switch identifier {
//        case "OptionsTableCell":
//            height = 5
//        default:
//            break
//        }
        return height
    }
    
    public func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let identifier = summary[indexPath.section].identifier
        switch identifier {
        case PaymentHomeConstants.Values.IdentifierNames.UPITableCell:
            router?.routeToUPI()
        default:
            break
        }
    }


}
