//
//  WalletAlertRouter.swift
//  Payment
//
//  Created by ANTONY RAPHEL on 16/12/18.
//  Copyright (c) 2018 Arpit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol WalletAlertRoutingLogic {
    func routeToPaymentHome()
}

protocol WalletAlertDataPassing {
    var dataStore: WalletAlertDataStore? { get }
}

class WalletAlertRouter: NSObject, WalletAlertRoutingLogic, WalletAlertDataPassing {
    weak var viewController: WalletAlertViewController?
    var dataStore: WalletAlertDataStore?
    
    // MARK: Routing
    
    func routeToPaymentHome() {
        viewController?.dismiss(animated: true, completion: nil)
    }
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: WalletAlertViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: WalletAlertDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
