//
//  WalletAlertPresenter.swift
//  Payment
//
//  Created by ANTONY RAPHEL on 16/12/18.
//  Copyright (c) 2018 Arpit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WalletAlertPresentationLogic {
    func presentSomething(response: WalletAlert.Something.Response)
    func presentConfirm(response: WalletAlert.Something.Response)
}

class WalletAlertPresenter: WalletAlertPresentationLogic {
    weak var viewController: WalletAlertDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: WalletAlert.Something.Response) {
        let viewModel = WalletAlert.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentConfirm(response: WalletAlert.Something.Response) {
        
    }
}
