//
//  WalletAlertViewController.swift
//  Payment
//
//  Created by ANTONY RAPHEL on 16/12/18.
//  Copyright (c) 2018 Arpit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WalletAlertDisplayLogic: class {
    func displaySomething(viewModel: WalletAlert.Something.ViewModel)
    func displayConfirm(viewModel: WalletAlert.Something.ViewModel)
}

class WalletAlertViewController: UIViewController, WalletAlertDisplayLogic {
    var interactor: WalletAlertBusinessLogic?
    var router: (NSObjectProtocol & WalletAlertRoutingLogic & WalletAlertDataPassing)?
    var confirmHandler: () -> Void = {}
    
    @IBOutlet weak var containerView: UIView!
    @IBOutlet weak var logoImageView: UIImageView!
    @IBOutlet weak var titleLabel: UILabel!
    @IBOutlet weak var descriptionLabel: UILabel!
    @IBOutlet weak var confirmButton: UIButton!
    @IBOutlet weak var dismissButton: UIButton!
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = WalletAlertInteractor()
        let presenter = WalletAlertPresenter()
        let router = WalletAlertRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        let blurEffect = UIBlurEffect(style: .light) // .extraLight or .dark
        let blurEffectView = UIVisualEffectView(effect: blurEffect)
        blurEffectView.frame = view.frame
        blurEffectView.alpha = 0.9
        view.insertSubview(blurEffectView, at: 0)
        containerView.dropShadow()
        containerView.layer.cornerRadius = 5
        confirmButton.layer.cornerRadius = 5
        doSomething()
    }
    
    // MARK: Do something
    
    @IBAction func didConfirm(_ sender: UIButton) {
        confirmHandler()
    }
    
    @IBAction func didDismiss(_ sender: UIButton) {
        router?.routeToPaymentHome()
    }
    
    func doSomething() {
        let request = WalletAlert.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: WalletAlert.Something.ViewModel) {

    }
    
    func displayConfirm(viewModel: WalletAlert.Something.ViewModel) {
        
    }
}
