//
//  WalletAlertInteractor.swift
//  Payment
//
//  Created by ANTONY RAPHEL on 16/12/18.
//  Copyright (c) 2018 Arpit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WalletAlertBusinessLogic {
    func doSomething(request: WalletAlert.Something.Request)
    func confirm(request: WalletAlert.Something.Request)
}

protocol WalletAlertDataStore {
    //var name: String { get set }
}

class WalletAlertInteractor: WalletAlertBusinessLogic, WalletAlertDataStore {
    var presenter: WalletAlertPresentationLogic?
    var worker: WalletAlertWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: WalletAlert.Something.Request) {
        worker = WalletAlertWorker()
        worker?.doSomeWork()
        
        let response = WalletAlert.Something.Response()
        presenter?.presentSomething(response: response)
    }
    
    func confirm(request: WalletAlert.Something.Request) {
        let response = WalletAlert.Something.Response()
        presenter?.presentConfirm(response: response)
    }
}
