//
//  NetBanksModels.swift
//  Payment
//
//  Created by ARPIT  SRIVASTAVA on 13/12/18.
//  Copyright (c) 2018 Arpit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum NetBanks {
    // MARK: Use cases
    
    enum List {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
}
