//
//  NetBanksPresenter.swift
//  Payment
//
//  Created by ARPIT  SRIVASTAVA on 13/12/18.
//  Copyright (c) 2018 Arpit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NetBanksPresentationLogic {
    func presentList(response: NetBanks.List.Response)
}

class NetBanksPresenter: NetBanksPresentationLogic {
    weak var viewController: NetBanksDisplayLogic?
    
    func presentList(response: NetBanks.List.Response) {
        let viewModel = getViewModel(from: response.banks)
        viewController?.displayList(viewModel: viewModel)
    }
    
    private func getViewModel(from banks: [NetBanks.List.Response.BankInfoResponse]) -> NetBanks.List.ViewModel {
        let allBanks = banks.map { NetBanks.List.ViewModel.BankInfoViewModel(name: $0.name) }
        let viewModel = NetBanks.List.ViewModel(banks: allBanks)
        return viewModel
    }
}
