//
//  NetBanksPresenter.swift
//  Payment
//
//  Created by ARPIT  SRIVASTAVA on 13/12/18.
//  Copyright (c) 2018 Arpit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NetBanksPresentationLogic {
    func presentList(response: NetBanks.List.Response)
}

class NetBanksPresenter: NetBanksPresentationLogic {
    weak var viewController: NetBanksDisplayLogic?
    
    func presentList(response: NetBanks.List.Response) {
        let viewModel = NetBanks.List.ViewModel()
        viewController?.displayList(viewModel: viewModel)
    }
}
