//
//  NetBanksInteractor.swift
//  Payment
//
//  Created by ARPIT  SRIVASTAVA on 13/12/18.
//  Copyright (c) 2018 Arpit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NetBanksBusinessLogic {
    func fetchList(request: NetBanks.List.Request)
}

protocol NetBanksDataStore {
    var banks: [String: Any] {get set}
}

class NetBanksInteractor: NetBanksBusinessLogic, NetBanksDataStore {
    var banks: [String: Any] = [:]
    
    var presenter: NetBanksPresentationLogic?
    
    func fetchList(request: NetBanks.List.Request) {
        let response = NetBanks.List.Response()
        presenter?.presentList(response: response)
    }
}
