//
//  CardPresenter.swift
//  Payment
//
//  Created by ARPIT  SRIVASTAVA on 12/12/18.
//  Copyright (c) 2018 Arpit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CardPresentationLogic {
    func presentSomething(response: Card.Something.Response)
}

class CardPresenter: CardPresentationLogic {
    weak var viewController: CardDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Card.Something.Response) {
        let viewModel = Card.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
