//
//  PaymentHomeRouter.swift
//  Payment
//
//  Created by ARPIT  SRIVASTAVA on 03/12/18.
//  Copyright (c) 2018 Arpit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PaymentHomeRoutingLogic {
    func routeToUPI()
    func routeToLinkWallet()
    func routeToPayWallet()
    func routeToMoreBanks()
    func routeToCard()
}

protocol PaymentHomeDataPassing {
    var dataStore: PaymentHomeDataStore? { get }
}

class PaymentHomeRouter: NSObject, PaymentHomeRoutingLogic, PaymentHomeDataPassing {
    weak var viewController: PaymentHomeViewController?
    var dataStore: PaymentHomeDataStore?
    
    // MARK: Routing
    func routeToUPI() {
        let sb = UIStoryboard(name: "Payment",
                              bundle: nil)
        let vc = sb.instantiateViewController(withIdentifier: "UPIViewController") as! UPIViewController
        viewController!.navigationController?.pushViewController(vc,
                                                 animated: true)
    }

    func routeToLinkWallet() {
        let sb = UIStoryboard(name: "Payment",
                              bundle: nil)
        let vc = sb.instantiateViewController(withIdentifier: "LinkWalletViewController") as! LinkWalletViewController
        viewController!.navigationController?.pushViewController(vc,
                                                                 animated: true)
    }
    
    func routeToPayWallet() {
        let sb = UIStoryboard(name: "Payment",
                              bundle: nil)
        let vc = sb.instantiateViewController(withIdentifier: "PayWalletViewController") as! PayWalletViewController
        viewController!.navigationController?.pushViewController(vc,
                                                                 animated: true)
    }

    func routeToMoreBanks() {
        let sb = UIStoryboard(name: "Payment",
                              bundle: nil)
        let vc = sb.instantiateViewController(withIdentifier: "NetBanksViewController") as! NetBanksViewController
        var destinationDS = vc.router!.dataStore!
        destinationDS.banksInfo = dataStore!.banksInfo
        viewController!.navigationController?.pushViewController(vc,
                                                                 animated: true)
    }
    
    func routeToCard() {
        let sb = UIStoryboard(name: "Payment",
                              bundle: nil)
        let vc = sb.instantiateViewController(withIdentifier: "CardViewController") as! CardViewController
        viewController!.navigationController?.pushViewController(vc,
                                                                 animated: true)
    }
}
